version: 2
jobs:
  setup: &exector
    working_directory: ~/work
    docker:
      - image: circleci/node:10.15
    environment:
      APP_PROJECT_NAME: profile-text-generator
    steps:
      - checkout
      - restore_cache:
          name: Restore npm dependencies
          key: npm-{{ checksum "./package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          name: Cache npm dependencies
          key: npm-{{ checksum "./package-lock.json" }}-{{ .Environment.CACHE_VERSION_NPM }}
          paths:
            - ~/work/node_modules
      - persist_to_workspace: &save_workspace
          root: .
          paths:
            - ./*
  lint:
    <<: *exector
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Eslint
          command: npm run lint:js
      - run:
          name: Run Stylelint
          command: npm run lint:css
  build:
    <<: *exector
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Build
          command: npm run build
      - persist_to_workspace:
          <<: *save_workspace
  deploy:
    <<: *exector
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: create gcp credential
          command: |
            echo $FIREBASE_SERVICE_KEY | base64 --decode --ignore-garbage > ~/firebase-service-key.json
      - run:
          name: deploy to storage
          command: |
            gcloud auth activate-service-account --key-file ~/firebase-service-key.json
            gsutil cp ./dist/$APP_PROJECT_NAME-latest.min.js gs://quwtara-tamago-don.appspot.com/scripts/$APP_PROJECT_NAME/$APP_PROJECT_NAME-master.min.js
  release:
    <<: *exector
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: create gcp credential
          command: |
            echo $FIREBASE_SERVICE_KEY | base64 --decode --ignore-garbage > ~/firebase-service-key.json
      - run:
          name: deploy to storage
          command: |
            gcloud auth activate-service-account --key-file ~/firebase-service-key.json
            gsutil cp gs://quwtara-tamago-don.appspot.com/scripts/$APP_PROJECT_NAME/$APP_PROJECT_NAME-master.min.js gs://quwtara-tamago-don.appspot.com/scripts/$APP_PROJECT_NAME/$APP_PROJECT_NAME-latest.min.js
            gsutil cp gs://quwtara-tamago-don.appspot.com/scripts/$APP_PROJECT_NAME/$APP_PROJECT_NAME-master.min.js gs://quwtara-tamago-don.appspot.com/scripts/$APP_PROJECT_NAME/$APP_PROJECT_NAME-$CIRCLE_TAG.min.js
workflows:
  version: 2
  deploy_to_storage:
    jobs:
      - setup:
          filters:
            tags:
              ignore: /.*/
      - lint:
          requires:
            - setup
          filters:
            tags:
              ignore: /.*/
      - build:
          requires:
            - lint
          filters:
            tags:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
            branches:
              only: 
                - master
      - release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
